### ISSUE TITLE
kubernetes-master/0* eroor         hook failed: "install"

### ISSUE THREAD

**Issue by rahulbca18** [juju-solutions/bundle-canonical-kubernetes#487] opened 2018-02-02 18:03 UTC
when i am going to install kubernet by juju then i am getting the given juju status 

Model    Controller  Cloud/Region         Version  SLA
default  lxd         localhost/localhost  2.3.2    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                         waiting    0/1  easyrsa                jujucharms   27  ubuntu  
etcd                            error        3  etcd                   jujucharms   63  ubuntu  
flannel                         waiting      0  flannel                jujucharms   40  ubuntu  
kubeapi-load-balancer  1.10.3   active       1  kubeapi-load-balancer  jujucharms   43  ubuntu  exposed
kubernetes-master               error        1  kubernetes-master      jujucharms   78  ubuntu  exposed
kubernetes-worker               error        3  kubernetes-worker      jujucharms   81  ubuntu  exposed
tomcat                          waiting    0/1  tomcat                 jujucharms    3  ubuntu  exposed

Unit                      Workload     Agent       Machine  Public address  Ports  Message
easyrsa/0                 waiting      allocating  0/lxd/0                         waiting for machine
etcd/0*                   blocked      executing   0        10.34.190.161          (install) Missing relation to certificate authority.
etcd/1                    error        idle        2        10.34.190.14           hook failed: "install"
etcd/2                    error        idle        3        10.34.190.223          hook failed: "install"
kubeapi-load-balancer/0*  active       idle        4        10.34.190.224          NGINX is ready
kubernetes-master/0*      error        idle        0        10.34.190.161          hook failed: "install"
kubernetes-worker/0*      maintenance  executing   1        10.34.190.221          (install) Installing kubectl snap
kubernetes-worker/1       error        idle        5        10.34.190.88           hook failed: "install"
kubernetes-worker/2       error        idle        6        10.34.190.247          hook failed: "install"
tomcat/0                  waiting      allocating  7                               waiting for machine

Machine  State    DNS            Inst id        Series  AZ  Message
0        started  10.34.190.161  juju-ad3ef9-0  xenial      Running
0/lxd/0  down                    pending        xenial      can't get info for image 'juju/xenial/amd64': not found
1        started  10.34.190.221  juju-ad3ef9-1  xenial      Running
2        started  10.34.190.14   juju-ad3ef9-2  xenial      Running
3        started  10.34.190.223  juju-ad3ef9-3  xenial      Running
4        started  10.34.190.224  juju-ad3ef9-4  xenial      Running
5        started  10.34.190.88   juju-ad3ef9-5  xenial      Running
6        started  10.34.190.247  juju-ad3ef9-6  xenial      Running
7        down                    pending        trusty      failed to start machine 7 (can't get info for image 'juju/trusty/amd64': not found), retrying in 10s (10 more attempts)

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular      joining  
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      joining  
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      joining  
etcd:cluster                         etcd:cluster                         etcd              peer         joining  
etcd:db                              flannel:etcd                         etcd              regular      joining  
etcd:db                              kubernetes-master:etcd               etcd              regular      joining  
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate  joining  
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      
kubernetes-master:kube-api-endpoint  kubernetes-worker:kube-api-endpoint  http              regular      joining  
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      joining  
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate  joining  
tomcat:cluster                       tomcat:cluster                       tomcat-cluster    peer         joining

**Comment by tvansteenburgh** [comment] 2018-02-02 18:23
Did you deploy using [conjure-up](https://conjure-up.io/)? If not, I recommend doing so, as it creates the proper lxd profile for deploying to localhost.

**Comment by rahulbca18** [comment] 2018-02-03 16:42
Thanks for you reply I have installed by conjure-up

**Comment by rahulbca18** [comment] 2018-02-05 03:59
When I was deployed kubernet-core it was ok but when i restart my laptop then it gives me error like

Model    Controller  Cloud/Region         Version  SLA
default  lxd-test    localhost/localhost  2.3.2    unsupported

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
easyrsa                         error        1  easyrsa                jujucharms   27  ubuntu  
etcd                            error        3  etcd                   jujucharms   63  ubuntu  
flannel                         waiting      0  flannel                jujucharms   40  ubuntu  
kubeapi-load-balancer           error        1  kubeapi-load-balancer  jujucharms   43  ubuntu  exposed
kubernetes-master               error        1  kubernetes-master      jujucharms   78  ubuntu  
kubernetes-worker               error        3  kubernetes-worker      jujucharms   81  ubuntu  exposed
mysql                           unknown      1  mysql                  jujucharms   55  ubuntu  
wiki                            unknown      1  mediawiki              jujucharms    5  ubuntu  

Unit                      Workload  Agent  Machine  Public address  Ports     Message
easyrsa/0*                error     idle   2        10.40.89.97               hook failed: "install"
etcd/0*                   error     idle   3        10.40.89.93               hook failed: "install"
etcd/1                    error     idle   4        10.40.89.22               hook failed: "install"
etcd/2                    error     idle   5        10.40.89.160              hook failed: "install"
kubeapi-load-balancer/0*  error     idle   6        10.40.89.171              hook failed: "install"
kubernetes-master/0*      error     idle   7        10.40.89.104              hook failed: "install"
kubernetes-worker/0       error     idle   8        10.40.89.35               hook failed: "install"
kubernetes-worker/1*      error     idle   9        10.40.89.153              hook failed: "install"
kubernetes-worker/2       error     idle   10       10.40.89.88               hook failed: "install"
mysql/0*                  unknown   idle   0        10.40.89.129    3306/tcp  
wiki/0*                   unknown   idle   1        10.40.89.183    80/tcp    

Machine  State    DNS           Inst id         Series  AZ  Message
0        started  10.40.89.129  juju-272cfb-0   trusty      Running
1        started  10.40.89.183  juju-272cfb-1   trusty      Running
2        started  10.40.89.97   juju-272cfb-2   xenial      Running
3        started  10.40.89.93   juju-272cfb-3   xenial      Running
4        started  10.40.89.22   juju-272cfb-4   xenial      Running
5        started  10.40.89.160  juju-272cfb-5   xenial      Running
6        started  10.40.89.171  juju-272cfb-6   xenial      Running
7        started  10.40.89.104  juju-272cfb-7   xenial      Running
8        started  10.40.89.35   juju-272cfb-8   xenial      Running
9        started  10.40.89.153  juju-272cfb-9   xenial      Running
10       started  10.40.89.88   juju-272cfb-10  xenial      Running

Relation provider                    Requirer                             Interface         Type         Message
easyrsa:client                       etcd:certificates                    tls-certificates  regular      joining
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      joining
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      joining
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      joining
etcd:cluster                         etcd:cluster                         etcd              peer         joining
etcd:db                              flannel:etcd                         etcd              regular      joining
etcd:db                              kubernetes-master:etcd               etcd              regular      joining
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      joining
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      joining
kubernetes-master:cni                flannel:cni                          kubernetes-cni    subordinate  joining
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      joining
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      joining
kubernetes-worker:cni                flannel:cni                          kubernetes-cni    subordinate  joining
mysql:cluster                        mysql:cluster                        mysql-ha          peer
mysql:db                             wiki:db                              mysql             regular


Help me why it is coming.

**Comment by ktsakalozos** [comment] 2018-02-05 08:08
Hi @rahulbca18,

We will need more information on what happens in your system. Would you please run this tool https://github.com/juju-solutions/cdk-field-agent and send us back the debug information it gathered? You should be able to see why the deployment is failing with a `juju debug-log`.

We appreciate your feedback. Thanks

**Comment by wwwtyro** [comment] 2018-02-16 19:56
@rahulbca18 Unfortunately, I was unable to reproduce this. I'm going to close this issue for now, but if you see it again, please reopen it with the output from cdk-field-agent as requested by @ktsakalozos above. Thanks for your bug report!

**Closed by wwwtyro** 2018-02-16 19:56 UTC
