### ISSUE TITLE
etcd units are not properly added as kubernetes componentstatuses

### ISSUE THREAD

**Issue by axinojolais** [juju-solutions/bundle-canonical-kubernetes#154] opened 2016-12-15 14:09 UTC
Hi,

I deployed a k8s cluster with 3 etcd units and an easyrsa unit for PKI management, but only one etcd appears in `kubectl get cs` : 

```
$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                    ERROR
scheduler            Healthy     ok                                                                         
controller-manager   Healthy     ok                                                                         
etcd-0               Unhealthy   Get https://10.25.63.163:2379/health: remote error: tls: bad certificate   
```

The status on the etcd cluster looks good though :

```
# etcdctl member list
5d08cf9fb83a4e04: name=etcd1 peerURLs=https://10.25.63.164:2380 clientURLs=https://10.25.63.164:2379
c09c82733b0b612c: name=etcd2 peerURLs=https://10.25.63.165:2380 clientURLs=https://10.25.63.165:2379
feb506089ee92e8f: name=etcd0 peerURLs=https://10.25.63.163:2380 clientURLs=https://10.25.63.163:2379
```

```
# etcdctl cluster-health
member 5d08cf9fb83a4e04 is healthy: got healthy result from https://10.25.63.164:2379
member c09c82733b0b612c is healthy: got healthy result from https://10.25.63.165:2379
member feb506089ee92e8f is healthy: got healthy result from https://10.25.63.163:2379
cluster is healthy
```

Yesterday I did the same kind of deploy, and I had 2 etcd cs (and not one).

What logs do you need to debug this ?

PS : the status in "kubectl get cs" is wrong because of https://github.com/kubernetes/kubernetes/issues/27343 and https://github.com/kubernetes/kubernetes/issues/35773

**Comment by mbruzek** [comment] 2016-12-15 15:53
@axinojolais What revision of the etcd charm were you using when you got this error? We are in the middle of a pretty big release for the kubernetes version 1.5.1 and have released a new etcd charm revision 21 that handles tls differently than before. Can you redeploy and see if you encounter this error again? If so please provide the steps to reproduce. Thanks!

**Comment by chuckbutler** [comment] 2016-12-16 01:42
This wont change even with the new release of ETCD. Kubernetes component status is not using the TLS certificates. Instead, as i understand it, they are using a simple curl against the etcd endpoint and since its a self signed cert, it will never properly return a TLS response that kubernetes is happy with.

I'll follow up with the Container Linux peeps and see if they can get me some additional insight into this, but it should not be a blocking bug, as etcd is indeed, functioning as expected.

**Comment by axinojolais** [comment] 2016-12-19 08:44
I'm mostly reporting the bad number of etcd units in `kubectl get cs`. There is only 1, I should have 3. The TLS status thing has already been reported in upstream k8s where it belongs.

**Comment by axinojolais** [comment] 2016-12-20 09:34
It was with the etcd charm revision 20. Let me try with version 21.

**Comment by axinojolais** [comment] 2016-12-20 11:17
The same issue happens with version 21. I only get one etcd in ```kubectl get cs```, when I should have 3. Perhaps this is related to https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/153 ?

**Comment by chuckbutler** [comment] 2017-01-03 18:04
I don't think you're going to see all 3 of those etcd services. Kubernetes even though it has 3 will only attempt to contact the first unit in the cluster unless i'm mistaken. Only if it fails contacting that unit will it progress to the next unit listed in the comma separated cluster string.

I do believe this is working as intended, but its not what we expected. So the question then becomes should component status really be reporting on 3 or is it only reporting that i has one etcd unit that its communicating with, and we're OK because it has an etcd connection for the datastore?

I guess in reality I dont know why we expect to see the 3 units of etd listed as component status. You can scale independent component statuses like the dashboard (even in different namespaces) and it wont update the CS URL or instance number for the dashboard (granted, pod vs external service) but this seems like we're over-thinking the CS view, which is typically full of lies anyway. It only checks for the existence of the object in kubernetes, not that its actually up and running, which can be observed by intentionally crashing a component and seeing it still listed as green.

**Comment by jacekn** [comment] 2017-03-16 12:33
In my deployment "kubectl get cs" matches "--etcd-servers" config option. Currently set to 2 out of 3 etcd cluster members.

If kubernetes is not configured to talk to all etcd instances how can we ensure HA?

An example:
k8s is configured to talk to a single etcd URL. That etcd instance goes down. etcd cluster is still fine, 2 out of 3 nodes are up. How will k8s talk to the cluster?

I did some troubleshooting and I think it's to do with relation data:
```
$ juju run --unit kubernetes-master/0 "relation-get -r etdc:11 - etcd/0"|grep connection
connection_string: https://<ip1>:2379,https://<ip2>:2379
$ juju run --unit kubernetes-master/0 "relation-get -r etdc:11 - etcd/1"|grep connection
connection_string: https://<ip1>:2379
$ juju run --unit kubernetes-master/0 "relation-get -r etdc:11 - etcd/2"|grep connection
connection_string: https://<ip1>:2379,https://<ip3>:2379
```

I suspect that once connection_string on all 3 relations contains all 3 cluster members "kubectl get cs" will show 3 etcd server too.

**Comment by chuckbutler** [comment] 2017-04-04 16:31
@jacekn this was resolved with https://github.com/juju-solutions/layer-etcd/pull/84

**Closed by chuckbutler** 2017-04-04 16:31 UTC
Labels: bug, etcd
