### ISSUE TITLE
localhost install: wrong version of CUDA installed?

### ISSUE THREAD

**Issue by rueberger** [juju-solutions/bundle-canonical-kubernetes#452] opened 2017-12-11 04:18 UTC
First of all, my thanks to the maintainers - quite a useful tool. And a disclaimer, I've just discovered `juju`, so please forgive my lack of understanding :)

I've encountered a problem installing to localhost though - I believe the wrong version of CUDA was installed on the k8s workers. The host system is running CUDA `9.0.76`,  CUDA 8 was installed on the workers.

`juju ssh kubernetes-worker/0 "nvidia-smi"` fails with `Failed to initialize NVML: Unknown Error`.

I tried running `juju config kubernetes-worker cuda-version=9.0.176`, followed by `juju run-action kubernetes_worker/{#}  upgrade`

CUDA 9 is installed on the workers but once complete `juju status` shows

```
Unit                      Workload  Agent  Machine  Public address  Ports           Message
easyrsa/0*                active    idle   0        10.60.149.156                   Certificate Authority connected.
etcd/0*                   active    idle   3        10.60.149.39    2379/tcp        Healthy with 3 known peers
etcd/1                    active    idle   4        10.60.149.99    2379/tcp        Healthy with 3 known peers
etcd/2                    active    idle   5        10.60.149.43    2379/tcp        Healthy with 3 known peers
kubeapi-load-balancer/0*  active    idle   1        10.60.149.101   443/tcp         Loadbalancer ready.
kubernetes-master/0*      active    idle   2        10.60.149.141   6443/tcp        Kubernetes master running.
  flannel/0*              active    idle            10.60.149.141                   Flannel subnet 10.1.81.1/24
kubernetes-worker/0*      error     idle   9        10.60.149.46    80/tcp,443/tcp  hook failed: "config-changed"
  flannel/3               active    idle            10.60.149.46                    Flannel subnet 10.1.27.1/24
kubernetes-worker/1       error     idle   10       10.60.149.203   80/tcp,443/tcp  hook failed: "config-changed"
  flannel/1               active    idle            10.60.149.203                   Flannel subnet 10.1.64.1/24
kubernetes-worker/2       error     idle   11       10.60.149.147   80/tcp,443/tcp  hook failed: "config-changed"
  flannel/2               active    idle            10.60.149.147                   Flannel subnet 10.1.87.1/24
```

Any ideas? Has GPU support been successfully tested on localhost deployments?

**Comment by marcoceppi** [comment] 2017-12-11 09:18
Howdy! Thanks for the report.

For localhost we use LXC machines, and I don't believe we expose the graphics cards from the host into the machines, I can't speak for testing coverage but I don't believe this scenario is tested (or supported). That said, we may be able to get this working/tested - I'll create a machine somewhere with a GPU and try to pass through the device in a localhost install.

**Comment by ktsakalozos** [comment] 2017-12-11 09:19
Hi @rueberger ,

Thank you for using CDK. As you realised CUDA support on localhost deployments would require the host and guest libraries to align. This might become a challenge sometimes.

First of all, would you be able to run the script in https://github.com/juju-solutions/cdk-field-agent and share the results so we can get some insight on what was the error encountered? The error/exception should also be present in the juju debug-log output.

Second, I assume you used conjure-up to deploy CDK on localhost. Can you please set the desired cuda version at the very beginning of the deployment? In the "Review and configure applications" step you can select "Configure" on the kubernetes-worker, then "Show Advance Configuration" and then you can replace the cuda-version. Also it would be helpful if we could reproduce your setup. Are you deploying on a local physical machine or did you get a GPU equipped instance from a cloud provider?

Thank you

**Comment by rueberger** [comment] 2017-12-12 00:49
Thanks for getting back to me -

@marcoceppi CUDA was installed on the workers though, surely this means the GPUs were exposed?

[Here's the output of cdk-field-agent](https://nofile.io/f/eJ5f8E8AgyT/results-2017-12-11-16-51-30.tar.gz), about 100MB. 

Yes, I used conjure-up. Thanks for the suggestion, I am having [some problems ](https://github.com/conjure-up/conjure-up/issues/1269) with conjure-down but I will try reinstalling with manually specified cuda-version and get back to you once that is resolved.

Yes, I am deploying to a local physical machine, running xenial.  What details would be useful to know?  Incidentally, I'm running 2 Titan Xp's. 

Much thanks,
A

**Comment by ktsakalozos** [comment] 2017-12-12 08:48
I cannot download the agent's output. NoFile.io says it is still being uploaded. I guess we will have to wait.

The specs of the machine (along with the software stack installed) would help us to reproduce the issue. Unfortunately this is a physical machine so it wouldn't help.

Thanks

**Comment by rueberger** [comment] 2017-12-12 18:21
Sorry about that, updated the link with a working download.

Well if it helps, [here's a gist](https://gist.github.com/rueberger/986d8d6e5346d44ebc5a6f938013feb1) with the output of `lshw` as well as lists of installed packages.

**Comment by rueberger** [comment] 2017-12-13 02:32
I think I've managed to narrow down the problem a bit.

As you suggested @ktsakalozos, I ran `conjure-up kubernetes`, changing the CUDA version to the desired `9.0.76` before deploying. (it fails)

Relevant part of `juju debug-log`:

```
unit-kubernetes-worker-0: 21:12:03 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/kubernetes_worker.py:229:set_app_version
unit-kubernetes-worker-0: 21:12:03 INFO unit.kubernetes-worker/0.juju-log Invoking reactive handler: reactive/cuda.sh "b'install_cuda\n'"
unit-kubernetes-worker-0: 21:12:04 DEBUG unit.kubernetes-worker/0.install Running reactive_handler_main for cuda.sh (invoke)
unit-kubernetes-worker-0: 21:12:04 DEBUG unit.kubernetes-worker/0.install Invoking bash reactive handler: install_cuda
unit-kubernetes-worker-0: 21:12:04 INFO unit.kubernetes-worker/0.juju-log Blacklisting nouveau module
unit-kubernetes-worker-0: 21:12:04 DEBUG unit.kubernetes-worker/0.install update-initramfs: Generating /boot/initrd.img-4.10.0-42-generic
unit-kubernetes-worker-0: 21:12:08 DEBUG unit.kubernetes-worker/0.install W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
unit-kubernetes-worker-0: 21:12:38 INFO unit.kubernetes-worker/0.juju-log Installing linux-image-extra
unit-kubernetes-worker-0: 21:12:38 INFO unit.kubernetes-worker/0.juju-log Running in a container. No need for the nVidia driver
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install --2017-12-13 02:12:38--  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.76-_amd64.deb
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|192.229.211.70|:80... connected.
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install HTTP request sent, awaiting response... 404 Not Found
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install 2017-12-13 02:12:38 ERROR 404: Not Found.
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install Traceback (most recent call last):
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/hooks/install", line 19, in <module>
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     main()
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 113, in main
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     bus.dispatch(restricted=restricted_mode)
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 364, in dispatch
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     _invoke(other_handlers)
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 340, in _invoke
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     handler.invoke()
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 242, in invoke
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     subprocess.check_call([self._filepath, '--invoke', self._test_output], env=os.environ)
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install     raise CalledProcessError(retcode, cmd)
unit-kubernetes-worker-0: 21:12:38 DEBUG unit.kubernetes-worker/0.install subprocess.CalledProcessError: Command '['/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/cuda.sh', '--invoke', b'install_cuda\n']' returned non-zero exit status 8
unit-kubernetes-worker-0: 21:12:38 ERROR juju.worker.uniter.operation hook "install" failed: exit status 1
```

So, at first glance, the problem appears to be that the URL defined in [this script](https://api.jujucharms.com/charmstore/v5/~containers/kubernetes-worker/archive/reactive/cuda.sh) is incorrect. I went to nvidia's site to investigate - CUDA 9 no longer appears to be (easily) available for download, as CUDA 9.1 has been released.  

I'm going to upgrade to CUDA 9.1 and try again.

Also, I thought it was curious that, although the script reported `Running in a container. No need for the nVidia driver`, it attempted to install CUDA anyways.

**Comment by ktsakalozos** [comment] 2017-12-13 07:41
That error explains a lot. You get a "404 Not found" for http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.0.76-_amd64.deb

If you go to http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ and search for what starts with cuda-repo you will spot cuda-repo-ubuntu1604_9.0.176-1_amd64.deb . The name of that deb package is constructed here: https://github.com/juju-solutions/layer-nvidia-cuda/blob/master/reactive/cuda.sh#L45

So the version you should be using is "9.0.176-1" for cuda 9.0.

Regarding the "Running in a container. No need for the nVidia driver", the charm will skip the call to this method: https://github.com/juju-solutions/layer-nvidia-cuda/blob/master/reactive/cuda.sh#L100 if running on lxd.

The cuda version handling needs some improvement. Do you have any suggestions? We could use a wildcard to denote we need the latest version of cuda in a series. For example if you set the config version to 9.0* we would need to look into the above repo and choose the latest cuda-repo starting with 9.0. What do you think? Should be an easy fix if you want to give it a try. Created this card on our backlog: https://trello.com/c/9GI7Uoo7/334-improve-cuda-version-handling

Thank you for your feedback. We appreciate you going through the code and trying to spot what is not clicking.

**Comment by rueberger** [comment] 2017-12-15 01:37
Not sure I would be much help, not much experience with bash scripting. Since the problem in this case stems from me manually changing `cuda-version` to a format not quite expected by the scripts, it might suffice just to throw a descriptive warning.  Seems like `cuda-version` is mostly script managed. 

What about just printing something to debug if `CUDA_SUB_VERSION` is unset, then setting it to 1?

We get a little further when I specify the CUDA version in the right format.

This is for `cuda-version = 9.1.85-1`:

```
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install --2017-12-15 00:27:50--  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_9.1.85-1_amd64.deb
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 192.229.211.70, 2606:2800:21f:3aa:dcf:37b:1ed6:1fb
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|192.229.211.70|:80... connected.
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install HTTP request sent, awaiting response... 200 OK
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Length: 2820 (2.8K) [application/x-deb]
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Saving to: 'cuda-repo-ubuntu1604_9.1.85-1_amd64.deb'
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install      0K ..                                                    100%  306M=0s
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install 2017-12-15 00:27:50 (306 MB/s) - 'cuda-repo-ubuntu1604_9.1.85-1_amd64.deb' saved [2820/2820]
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install (Reading database ... 40313 files and directories currently installed.)
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Preparing to unpack .../cuda-repo-ubuntu1604_9.1.85-1_amd64.deb ...
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Unpacking cuda-repo-ubuntu1604 (9.1.85-1) over (9.1.85-1) ...
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install Setting up cuda-repo-ubuntu1604 (9.1.85-1) ...
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install The public CUDA GPG key does not appear to be installed.
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install To install the key, run this command:
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
unit-kubernetes-worker-2: 19:27:50 DEBUG unit.kubernetes-worker/2.install
unit-kubernetes-worker-2: 19:27:54 DEBUG unit.kubernetes-worker/2.install W: GPG error: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80
unit-kubernetes-worker-2: 19:27:54 DEBUG unit.kubernetes-worker/2.install W: The repository 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release' is not signed.
```

Pretty straightforward,  need to add `apt-key add /var/${REPO_PKG}/7fa2af80.pub` after L164. Is there any reason to not do this? 

Of course, happy to help improve this awesome tool if I can. Thank you for helping me troubleshoot!

Is CUDA 9 officially supported at this time? Or am I bushwhacking my way through uncharted territory? :) Would love to help see it be officially supported if it's not

**Comment by ktsakalozos** [comment] 2017-12-18 10:08
Thank you for the `CUDA_SUB_VERSION` set to 1 if missing suggestion. We will take this into consideration when we work on the respective task.

On the warning you get for not having the apt key I do not see any reason why not to add it.

In respect to support for CUDA 9, it should be part of our GPU offering (at least in the long run). It is not currently our default. After setting the correct CUDA version do you have any indications showing CUDA 9 is not correctly setup?

We welcome any help in extending gpu support to all potential deployment scenarios. Would you be willing to "testdrive" upcoming beta releases before hitting the stable channel? This way we can ensure we do not break your setup (cuda 9 on localhost) by accident. What do you say?

**Comment by rueberger** [comment] 2017-12-18 21:30
Can't tell if CUDA 9 is correctly setup right now, installation halts at the key failure.

Absolutely, happy to testdrive beta releases. We will be putting CDK into production as soon as this is all squared away, but until then happy to play guinea pig.

What would be the recommended approach for adding the key change? Is there something I can fork? Or should I try finding that file in my system and manually modifying it?

**Comment by ktsakalozos** [comment] 2017-12-20 12:03
Sorry for my late response. There is an upcoming release that takes most of my time.

It is strange that this installation does not complete. I was expecting all packages to come from the same repo. Can you send an https://github.com/juju-solutions/cdk-field-agent output. Is your worker machines in an error state? What is the juju status output? You can always `juju ssh kubernetes-worker/?` and `apt-key add ...` after that you can `juju resolved kubernetes-worker/?` so that you mark the deployment issue as resolved and juju can continue with the rest of the installation.

Forking the cuda layer is the way to go if you want to ship your charms and test out your fixes. You should take a look at how charms are build https://jujucharms.com/docs/stable/developer-layer-example and remember that the charm layer you need to build is with the upstream kubernetes project  https://github.com/kubernetes/kubernetes/tree/master/cluster/juju/layers that depends on the cuda layer.

You mention you were going to put CDK in production. If you plan to also purchase support https://www.ubuntu.com/kubernetes there is another path we should follow. That path may involve solutions architects on site etc. Needless to say that we would be giving higher priority to your requests.

**Comment by ktsakalozos** [comment] 2017-12-21 18:46
Spent some time looking into this. Overall, the localhost+gpu setup is
hard to be officialy supported because we need a specific setup
on the host machine and we have no control over it.  

Regardless. Here is how you can deploy cdk on localhost with gpu support.
On the host machine you have CUDA installed (9.1 in our case).
You start conjure-up and select the cdk deployment on localhost.
On the advanced configuration options you set the desired cuda-version
that will be installed on the worker nodes (9.1.85-1 in our case).
The CUDA verion on the host and workers should match.
We need to address the missing repo signature. As a temporary workaround we
need to manually accept the signature on each worker node
 `juju run --application kubernetes-worker apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub`.
The workers will retry the CUDA installation and succeed.
CUDA installation takes a considerable amount of time since each worker
needs to fetch packages of a few GBs.
After the deployment, workers (running as LXC containers) have CUDA
installed but they do not have access to the host's GPU.
You need to enable GPU passthrough access to the lxc containers.
From juju status you have to find the machines the kubernetes-worker
application is running on. Each macine has a name of the form juju-XXXXXXX (eg juju-3aa518-0).
You need to add the gpu device to each worker machine.
This is done like so `lxc config device add juju-XXXXXXX gpu gpu` [1] for each worker.
After restarting the the worker machines everything should be in place.

In a production (non-localhost) environment, juju "owns" the host machine
so the required software stack is the one we would expect and there is no intermediate lxc layer.

You should also note that the gpu support on 1.9 k8s release has undergone significant changes.
We did not have the time to automate/streamline the respective gpu devops, therefore,
I would suggest you configure the channel config to 1.8/stable for now. 

[1] https://stgraber.org/2017/03/21/cuda-in-lxd/

**Comment by ktsakalozos** [comment] 2018-04-25 17:29
I am closing this.

The support for GPUs on localhost is straight forward now in the 1.10 release. Have a look at https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/561 and the instructions at https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Deploying-on-LXD

**Closed by ktsakalozos** 2018-04-25 17:29 UTC

**Comment by rueberger** [comment] 2018-04-25 22:40
Good to hear! Thanks for your help @ktsakalozos!
