### ISSUE TITLE
If keepalived deployed, master kubeconfig api-server endpoint should be the VIP

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundle-canonical-kubernetes#603] opened 2018-06-29 13:57 UTC
See https://github.com/juju-solutions/charm-keepalived/pull/1#discussion_r199074508

**Comment by dshcherb** [comment] 2019-02-18 06:52
In other words:

```
juju ssh kubernetes-master/0 grep server config
    server: https://<ip-address>:443
```

Instead, it should be equal to `vip` or `vip_hostname` configured in the keepalived charm. Config values 

```
juju config keepalived vip_hostname
kubeapilb.maas

juju config keepalived virtual_ip
192.0.2.200

juju ssh kubernetes-worker/0 grep server ~/.kube/config
    server: https://kubeapilb.maas:443
```

**Comment by Cynerva** [comment] 2019-02-19 14:38
This looks like a duplicate of https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/712 so I'm closing this.

See https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/712#issuecomment-456436156. If you relate `kubernetes-master:loadbalancer` to `keepalived:loadbalancer`, and remove any other relations to `kubernetes-master:loadbalancer` (e.g. to `kubeapi-load-balancer:loadbalancer`), then the kube config should be generated correctly.

**Closed by Cynerva** 2019-02-19 14:38 UTC
