### ISSUE TITLE
Ceph volume provisioning fails with "No such file or directory"

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/bundle-canonical-kubernetes#710] opened 2018-12-13 14:42 UTC
Originally reported by @grebennikov in https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/631.

> here is the paste from inside the container of csi-provisioner, that shows that the provisioning pod doesn't get the keyring and ceph config populated, thereforee cannot provision any volumes.
https://pastebin.ubuntu.com/p/39G5hv2xVN/

**Comment by grebennikov** [comment] 2018-12-14 16:13
@Cynerva quick update on this - while the cluster was running for quite some time, I've just killed the container of the provisioner. Kubernetes recreated it and was immediately able to provision the volume. To me it looks like there is a race condition in this case.

**Comment by hyperbolic2346** [comment] 2018-12-14 22:31
This all comes through the secret. I wonder if it isn't being populated first and there is a race here.

**Comment by grebennikov** [comment] 2018-12-14 22:42
Further on, even when it is able to provision the volume (and it shows up in Ceph) - from inside the container I can't dd anything to the volume, the operation just hangs.
If I remove the pod and try to delete the volume - the operation just hangs.

**Comment by grebennikov** [comment] 2018-12-17 19:21
Tried to re-provision the cluster from scratch and it is able to at least create the volume from the first attempt.
Also, I could successfully write into the volume and re-attach it to another pods.
Let's put this issue on hold and I'll try to reproduce it again.
If no success let's just consider it closed.

**Comment by joedborg** [comment] 2018-12-19 14:18
Hey @grebennikov, could you give me a few steps to attempt to reproduce please?  Have you just got CDK bundle + Ceph Mon and OSD charms?

**Comment by xannz** [comment] 2019-02-13 12:30
I'm running into the same issue
```
  Warning  ProvisioningFailed  5m  csi-rbdplugin csi-rbdplugin-provisioner-0 40f32c1c-2f87-11e9-bbc3-f25e566449b0  Failed to provision volume with StorageClass "ceph-xfs": rpc error: code = Unknown desc = failed to create rbd image, command output: 2019-02-13 12:15:37.004464 7fddbda08d40 -1 did not load config file, using default settings.
2019-02-13 12:15:37.021148 7fddbda08d40 -1 Errors while parsing config file!
2019-02-13 12:15:37.021169 7fddbda08d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.021172 7fddbda08d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.021173 7fddbda08d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.023037 7fddbda08d40 -1 Errors while parsing config file!
2019-02-13 12:15:37.023055 7fddbda08d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.023057 7fddbda08d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.023057 7fddbda08d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-02-13 12:15:37.068061 7fddbda08d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
rbd: error opening pool 'xfs-pool': (2) No such file or directory
: exit status 2
```

My juju env:
```
App                Version  Status  Scale  Charm              Store       Rev  OS      Notes
ceph-mon           12.2.8   active      1  ceph-mon           jujucharms   32  ubuntu  
ceph-osd           12.2.8   active      1  ceph-osd           jujucharms  276  ubuntu  
easyrsa            3.0.1    active      1  easyrsa            jujucharms  195  ubuntu  
etcd               3.2.10   active      1  etcd               jujucharms  378  ubuntu  
flannel            0.10.0   active      2  flannel            jujucharms  351  ubuntu  
kubernetes-master  1.13.3   active      1  kubernetes-master  jujucharms  542  ubuntu  exposed
kubernetes-worker  1.13.3   active      1  kubernetes-worker  jujucharms  398  ubuntu  exposed
```
It's a CDK core bundle with one ceph-mon / ceph-osd charm. After relating the ceph-mon with the k8s-master and trying to request a persistent volume claim.

Looking into the `csi-rbdplugin-provisioner` pod I see the following error:
```
E0213 12:28:06.882449       1 controller.go:1174] Error scheduling operaion "provision-sander-testing/gitlab-k8s-operator-volume-juju-operator-gitlab-k8s-0[89402887-2f88-11e9-b1fb-0050562c4bff]": Failed to create operation with name "provision-sander-testing/gitlab-k8s-operator-volume-juju-operator-gitlab-k8s-0[89402887-2f88-11e9-b1fb-0050562c4bff]". An operation with that name failed at 2019-02-13 12:26:52.127598101 +0000 UTC m=+1481.548811553. No retries permitted until 2019-02-13 12:28:54.127598101 +0000 UTC m=+1603.548811553 (2m2s). Last error: "rpc error: code = Unknown desc = failed to create rbd image, command output: 2019-02-13 12:26:52.051684 7fd5e78b1d40 -1 did not load config file, using default settings.\n2019-02-13 12:26:52.067548 7fd5e78b1d40 -1 Errors while parsing config file!\n2019-02-13 12:26:52.067564 7fd5e78b1d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.067567 7fd5e78b1d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.067567 7fd5e78b1d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.069411 7fd5e78b1d40 -1 Errors while parsing config file!\n2019-02-13 12:26:52.069429 7fd5e78b1d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.069431 7fd5e78b1d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.069432 7fd5e78b1d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory\n2019-02-13 12:26:52.113841 7fd5e78b1d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory\nrbd: error opening pool 'xfs-pool': (2) No such file or directory\n: exit status 2".
```

**Comment by hyperbolic2346** [comment] 2019-02-15 15:09
A shot in the dark here, but did you create the required pools as defined in the [docs](https://www.ubuntu.com/kubernetes/docs/storage)?

**Comment by xannz** [comment] 2019-02-15 16:08
I did not, thanks. These docs seem to be out of date then (for 1.13):
https://kubernetes.io/docs/getting-started-guides/ubuntu/storage

**Comment by hyperbolic2346** [comment] 2019-02-15 21:07
@xannz We're in the process of moving documentation to the link I gave. It is, unfortunately, a process.

On the up-side, you won't have to create those pools manually soon. @joedborg did some work recently to make the charm create those for you. That work hasn't been released yet, but should be out soonish.

**Comment by phausman** [comment] 2019-02-18 19:41
I'm running into the same issue as well. 

Error message:
https://paste.ubuntu.com/p/Bbz6Dr7YgB/

My bundles:
https://pastebin.ubuntu.com/p/XBVtwb5QgW/

Deployed into manually provisioned VMs with

```
juju deploy \
  --map-machines=existing,0=0,1=1,2=2,3=3,4=4,5=5,6=6,7=7,8=8,9=9,10=10 \
  --overlay ceph.yaml \
  --overlay nagios.yaml \
  bundle.yaml
```

**Comment by hyperbolic2346** [comment] 2019-02-19 01:00
@phausman you have the same issue. The interesting part of all that spew is
`rbd: error opening pool 'xfs-pool': (2) No such file or directory`

**Comment by phausman** [comment] 2019-02-19 06:42
> You need to create that pool or switch to the edge charm that will do it for you.

Thank you, @hyperbolic2346! You are right, I overlooked creating the pool. Now that it is created, all is good. 

Just for the future reference, creating the pools:
```
juju run-action ceph-mon/0 create-pool name=xfs-pool --wait
juju run-action ceph-mon/0 create-pool name=ext4-pool --wait
```

**Comment by joedborg** [comment] 2019-02-26 09:01
I believe this is fixed with documentation.  If anyone is still seeing the issue, please feel free to re-open with reproduction details.

Thanks!

**Closed by joedborg** 2019-02-26 09:01 UTC
Labels: field/normal, status/needs-feedback
