### ISSUE TITLE
Proxy settings not being communicated to docker daemon on workers.

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-canonical-kubernetes#320] opened 2017-06-27 19:17 UTC
Seems to require at least a docker daemon restart, and may also need a complete reset of proxy config via juju. This can prevent offline installation.

**Comment by tvansteenburgh** [comment] 2017-06-27 19:32
Bundle that didn't work: https://www.irccloud.com/pastebin/1tk72cTZ/

To get docker to respect the proxy settings, they had to be unset/set on the worker charm?

**Comment by chuckbutler** [comment] 2017-06-27 19:36
yep

https://github.com/juju-solutions/layer-docker#configuration

**Comment by ktsakalozos** [comment] 2017-07-19 11:34
I was not able to reproduce this. Things checked:

1. The docker layer deployed as a charm honours any initial configuration regarding proxy setup. This was tested with `juju deploy <local-build-of-docker> d3 --config conf.yaml` and the config  http://paste.ubuntu.com/25124894/

2. Deploying a slightly altered bundle on aws that a) did not include the machine constraints (some did not exist on aws) and b) the snap proxy was removed so we can deploy snaps. Here is the bundle used http://paste.ubuntu.com/25124915/ . This bundle propagated the proxy settings to docker running on the workers.

In the above tests docker was properly configured with the designated proxy settings as indicated by `docker info`, eg http://pastebin.ubuntu.com/25124926/

Could it be I am not testing proxy settings in the same way @SaMnCo did on site? Any suggestions/ideas on how to proceed with this?

**Comment by tvansteenburgh** [comment] 2018-05-14 13:58
Can't repro and no updates in almost a year, closing.

**Closed by tvansteenburgh** 2018-05-14 13:58 UTC
Labels: kind/bug, status/needs-feedback
