### ISSUE TITLE
kubeapi-load-balancer charm not respecting port configuration change

### ISSUE THREAD

**Issue by paul-oreilly** [juju-solutions/bundle-canonical-kubernetes#164] opened 2016-12-21 01:55 UTC
(As of commit a585523)

Using the "kubectl proxy" command from within the server that is in turn running the kubernetes cluster via LXD, connections to localhost:8001/ui timeout and the kubernetes dashboard is inaccessible.

> curl -IL localhost:8001/ui
> HTTP/1.1 301 Moved Permanently
> Content-Type: text/plain; charset=utf-8
> Date: Wed, 21 Dec 2016 00:40:04 GMT
> Location: /ui/
> Server: nginx/1.10.0 (Ubuntu)
> 
> HTTP/1.1 307 Temporary Redirect
> Content-Type: text/plain; charset=utf-8
> Date: Wed, 21 Dec 2016 00:40:05 GMT
> Location: /api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
> Server: nginx/1.10.0 (Ubuntu)
> 
> HTTP/1.1 301 Moved Permanently
> Content-Type: text/plain; charset=utf-8
> Date: Wed, 21 Dec 2016 00:40:05 GMT
> Location: /api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
> Server: nginx/1.10.0 (Ubuntu)
> 
> HTTP/1.1 504 Gateway Timeout
> Content-Length: 192
> Content-Type: text/html
> Date: Wed, 21 Dec 2016 00:41:35 GMT
> Server: nginx/1.10.0 (Ubuntu)

Connecting to the API's address directly required disabling curls security:

> curl -kL https://10.58.180.218:443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
> <html>
> <head><title>504 Gateway Time-out</title></head>
> <body bgcolor="white">
> <center><h1>504 Gateway Time-out</h1></center>
> <hr><center>nginx/1.10.0 (Ubuntu)</center>
> </body>
> </html>
> 

The API server itself is available - 

> curl -kL https://10.58.180.218
> {
>   "paths": [
>     "/api",
>     "/api/v1",
>     "/apis",
>     "/apis/apps",
>     "/apis/apps/v1beta1",  
>     "/apis/authentication.k8s.io",
>     "/apis/authentication.k8s.io/v1beta1",
>     "/apis/authorization.k8s.io",
>     "/apis/authorization.k8s.io/v1beta1",
>     "/apis/autoscaling",
>     "/apis/autoscaling/v1",
>     "/apis/batch",
>     "/apis/batch/v1",
>     "/apis/batch/v2alpha1",
>     "/apis/certificates.k8s.io",
>     "/apis/certificates.k8s.io/v1alpha1",
>     "/apis/extensions",
>     "/apis/extensions/v1beta1",
>     "/apis/policy",
>     "/apis/policy/v1beta1",  
>     "/apis/rbac.authorization.k8s.io",
>     "/apis/rbac.authorization.k8s.io/v1alpha1",
>     "/apis/storage.k8s.io",
>     "/apis/storage.k8s.io/v1beta1",
>     "/healthz",
>     "/healthz/poststarthook/bootstrap-controller",
>     "/healthz/poststarthook/extensions/third-party-resources",
>     "/healthz/poststarthook/rbac/bootstrap-roles",
>     "/logs",
>     "/metrics",
>     "/swaggerapi/",
>     "/ui/",
>     "/version"
>   ]
> }

Juju shows the cluster in good health

![fwpdvr8](https://cloud.githubusercontent.com/assets/439242/21374620/d0822082-c78c-11e6-853d-35e6f9766acf.png)

Kubernetes does show the dashboard running

![rmfgftg](https://cloud.githubusercontent.com/assets/439242/21374670/2e265c1c-c78d-11e6-9af9-df40033b75aa.png)

The command "kubectl proxy" left running in a isolated terminal gave a cryptic error

> ./kubectl proxy  
> Starting to serve on 127.0.0.1:8001I1221 01:37:19.818183  742116 logs.go:41] http: proxy error: net/http: request canceled  
> I1221 01:37:31.689161  742116 logs.go:41] http: proxy error: net/http: request canceled

**Comment by chuckbutler** [comment] 2017-01-10 17:53
Greetings paul, I've spent some time this morning trying to reproduce this bug and haven't managed a reproduction. Do you still have the model available for further inspection?

**Comment by paul-oreilly** [comment] 2017-01-10 21:58
I still have the cluster running on a server set aside for the purpose, and can provide access if that helps? (if you send me a SSH key, I'm quite happy for you to login and poke it if that helps!)

The timeout response seems in my limited understanding might be a firewall issue. Having completely disabled the firewall for testing, the current results are...

> curl localhost:8001
> <h3>Unauthorized</h3>

Attempting a connection to the load balancer for the kubernetes API directly: 

> curl -kL https://10.58.180.218:443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
> <html>
> <head><title>504 Gateway Time-out</title></head>
> <body bgcolor="white">
> <center><h1>504 Gateway Time-out</h1></center>
> <hr><center>nginx/1.10.0 (Ubuntu)</center>
> </body>
> </html>

Both connection attempts are being made from the 'docker' user on the server which kubectl is configured to work with. (The same server running the LXD containers for kubernetes)

There's some discussion that may be helpful on the issue here - https://github.com/kubernetes/dashboard/issues/692

It looks like there is a need for a guide to either generating a credential set for kubectl for a workstation outside the cluster, or a setup that publicly exposes the web UI - which then has very significant security concerns. (An SSH tunnel can solve that, but that assumes a correctly established firewall - which seems to need a guide of it's own)

**Comment by paul-oreilly** [comment] 2017-01-10 22:28
The dashboards check to enforce access from localhost can be disabled by 

> kubectl proxy --accept-hosts='^*$'

The result remains an "Unauthorized" response on my setup using just "curl localhost:8001".
Attempting "curl localhost:8001/ui" times out.

**Comment by wwwtyro** [comment] 2017-01-19 16:45
@chuckbutler Did you guys find a resolution for this issue?

**Comment by chuckbutler** [comment] 2017-01-19 19:33
@wwwtyro i haven't been able to reproduce to this date, but paul has indicated there is a cluster for us to poke at. If you've got the time it would be a good exercise to investigate and see whats happening. Can I tap you for point on this @wwwtyro?

**Comment by kwtalley** [comment] 2017-02-06 01:17
had a very similar issue going on (504 bad gateway) yet juju status was completely green. in my case, i was running a kubeapi-lb/master/worker combined. i had changed the kubeapi-lb port to 4443, yet saw kubectl commands failing in 'juju debug-log' from all the workers with a message like "failed to connect to correct_lb_ip:4443 : connection refused". traced it back to the actual nginx config on the kubeapi-lb/master/worker node: /etc/nginx/sites-enabled/apilb. it was still set to port 443 and not 4443 so it definitely didn't get the port config. changed it, restarted nginx, everything works now and don't need the "kubectl proxy" to get to the dashboard.

**Comment by tvansteenburgh** [comment] 2018-12-21 05:46
@joedborg Can you take a look at this and see if this is still an issue, or if it's been fixed along the way somewhere?

**Comment by joedborg** [comment] 2018-12-21 13:55
I can't reproduce it from the steps listed above.  

@paul-oreilly, @wwwtyro, @kwtalley are any of you still seeing this issue?

**Comment by joedborg** [comment] 2019-01-16 18:56
I believe this is resolved by the PR above, please reopen if you feel this isn't the case.

**Closed by joedborg** 2019-01-16 18:56 UTC
Labels: area/kube-api-loadbalancer, kind/bug
